//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveirosID.Models {

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Compras {
        // Inicializa a ListadeArtigos associada a cada compra
        public Compras() {
            ListadeArtigos = new HashSet<CompraArtigo>();
            ListadeUtilizadores = new HashSet<UtilizadorCompra>();
        }

        // Chave Primaria da Tabela Compra
        [Key]
        public int CompraID { get; set; }

        public string metodoentrega { get; set; }

        public string metodopagamento { get; set; }

        public string estado { get; set; }

        public DateTime data { get; set; }

        public float precototal { get; set; }

        // Para cada Compra existe um Utilizador
        // Chave forasteira para Utilizador

        public virtual ICollection<CompraArtigo> ListadeArtigos { get; set; }

        public virtual ICollection<UtilizadorCompra> ListadeUtilizadores { get; set; }
    }
}
