//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveirosID.Models {

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Compras {
        // Inicializa a ListadeArtigos associada a cada compra
        public Compras() {
            ListadeArtigos = new HashSet<CompraArtigo>();
        }

        // Chave Primaria da Tabela Compra
        [Key]
        public int CompraID { get; set; }

        public string Metodoentrega { get; set; }

        public string Metodopagamento { get; set; }

        public string Estado { get; set; }

        public DateTime Data { get; set; }

        public double Precototal { get; set; }

        // Para cada Compra existe um Utilizador
        // Chave forasteira para Utilizador

        // Cria uma Chave forasteira para a variavel Artigo
        [ForeignKey("Utilizador")]
        public int UtilizadorFK { get; set; }  

        public virtual Utilizadores Utilizador { get; set; }

        public virtual ICollection<CompraArtigo> ListadeArtigos { get; set; }
    }
}
