//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveirosID.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.CompraArtigoes = new HashSet<CompraArtigoes>();
        }
    
        public int CompraID { get; set; }
        public string metodoentrega { get; set; }
        public string metodopagamento { get; set; }
        public string estado { get; set; }
        public System.DateTime data { get; set; }
        public float precototal { get; set; }
        public int UtilizadorFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraArtigoes> CompraArtigoes { get; set; }
        public virtual Utilizadores Utilizadores { get; set; }
    }
}
