//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveirosID.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelodeBasedeDados : DbContext
    {
        public ModelodeBasedeDados()
            : base("name=ModelodeBasedeDados")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Artigos> Artigos { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CarrinhoArtigoes> CarrinhoArtigoes { get; set; }
        public virtual DbSet<Carrinhos> Carrinhos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CompraArtigoes> CompraArtigoes { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<ContentViewModels> ContentViewModels { get; set; }
        public virtual DbSet<Imagens> Imagens { get; set; }
        public virtual DbSet<UtilizadorCompras> UtilizadorCompras { get; set; }
        public virtual DbSet<Utilizadores> Utilizadores { get; set; }
    }
}
