//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViveirosID.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigos> Artigos { get; set; }
        public virtual DbSet<CarrinhoArtigoes> CarrinhoArtigoes { get; set; }
        public virtual DbSet<Carrinhos> Carrinhos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CompraArtigoes> CompraArtigoes { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<Imagens> Imagens { get; set; }
        public virtual DbSet<Utilizadores> Utilizadores { get; set; }
    }
}
